# version: '3.8'

# services:
#   frontend:
#     build:
#       context: ./frontend
#       args:
#         VITE_BACKEND_URL: https://api.forever.aimablem.dev
#     ports:
#       - "3100:80"
#     depends_on:
#       - backend
#     networks:
#       - appnet

#   backend:
#     build: ./backend
#     ports:
#       - "4100:4000"
#     depends_on:
#       - mongodb
#     environment:
#       - JWT_SECRET=
#       - ADMIN_EMAIL=
#       - ADMIN_PASSWORD=
#       - MONGODB_URI=
#       - CLOUDINARY_API_KEY=
#       - CLOUDINARY_SECRET_KEY=
#       - CLOUDINARY_NAME=
#       - STRIPE_SECRET_KEY=
#     networks:
#       - appnet

#   mongodb:
#     image: mongo:latest
#     restart: always
#     volumes:
#       - forever_mongo_data:/data/db
#     networks:
#       - appnet

# volumes:
#   forever_mongo_data:

# networks:
#   appnet:
#     driver: bridge
# рабочий скрипт без мониторинга version: '3.8'

# services:
#   frontend:
#     build:
#       context: ./frontend
#       args:
#         VITE_BACKEND_URL: https://api.forever.aimablem.dev
#     ports:
#       - "3100:80"
#     depends_on:
#       - backend
#     networks:
#       - appnet

#   backend:
#     build: ./backend
#     ports:
#       - "4100:4000"
#     depends_on:
#       - mongodb
#     env_file:
#       - ./backend/.env
#     networks:
#       - appnet

#   mongodb:
#     image: mongo:latest
#     restart: always
#     volumes:
#       - forever_mongo_data:/data/db
#     networks:
#       - appnet

# volumes:
#   forever_mongo_data:

# networks:
#   appnet:
#     driver: bridge

#   prometheus:
#     image: prom/prometheus
#     container_name: prometheus
#     volumes:
#       - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
#     ports:
#       - "9090:9090"
#     networks:
#       - appnet

#   grafana:
#     image: grafana/grafana
#     container_name: grafana
#     ports:
#       - "3000:3000"
#     depends_on:
#       - prometheus
#     networks:
#       - appnet

version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        VITE_BACKEND_URL: https://api.forever.aimablem.dev
    ports:
      - "3100:80"
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    build: ./backend
    ports:
      - "4100:4000"
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    networks:
      - appnet

  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - forever_mongo_data:/data/db
    networks:
      - appnet

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - appnet

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - appnet
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  forever_mongo_data:
  grafana-storage:

networks:
  appnet:
    driver: bridge
